#reading in and manipulating hwinfo graphs for games
```{r}
library(tidyverse)
library(readxl)
library(lubridate) #for date extraction and manipulation
library(ggthemes)
library(tools) #for toTitleCase function (makes strings into propercase)

excel_file_hwinfo = "C:/Users/Ryan/Coding Projects/Computer Benchmark/Data/hwinfo_test.xlsx"

hwinfo_ow <- read_excel(excel_file_hwinfo, sheet = "hwinfo_ow")
hwinfo_destiny <- read_excel(excel_file_hwinfo, sheet = "hwinfo_destiny")
hwinfo_r6 <- read_excel(excel_file_hwinfo, sheet = "hwinfo_r6")
hwinfo_gtav <- read_excel(excel_file_hwinfo, sheet = "hwinfo_gtav")
hwinfo_apex <- read_excel(excel_file_hwinfo, sheet = "hwinfo_apex")
hwinfo_rl <- read_excel(excel_file_hwinfo, sheet = "hwinfo_rl")
hwinfo_battlefront <- read_excel(excel_file_hwinfo, sheet = "hwinfo_battlefront")
hwinfo_halo <- read_excel(excel_file_hwinfo, sheet = "hwinfo_halo")
hwinfo_fortnite <- read_excel(excel_file_hwinfo, sheet = "hwinfo_fortnite")
hwinfo_cod <- read_excel(excel_file_hwinfo, sheet = "hwinfo_cod")


#Creating a list of dataframes from above  
df_list_hw <- list(hwinfo_ow, hwinfo_destiny, hwinfo_r6, hwinfo_gtav, hwinfo_apex, hwinfo_rl, hwinfo_battlefront, hwinfo_halo, hwinfo_fortnite, hwinfo_cod)

# Rename each data frame in the list to match its sheet name
names(df_list_hw) <- c("overwatch", "destiny", "r6", "gtav", "apex", "rocket_league", "battlefront", "halo", "fortnite", "cod")

# Remove the last 2 rows from each data frame
df_list_hw <- lapply(df_list_hw, function(df) head(df, -2))

# Convert all columns (except for the date column) to numeric then recombines original date variable to numeric dataset
df_list_hw <- lapply(df_list_hw, function(df) {
  df_num <- as.data.frame(lapply(df[-1], as.numeric))
  cbind(df[1], df_num)
})

# Rename the date column to "DateTime"
df_list_hw <- lapply(df_list_hw, function(df) {
  names(df)[1] <- "DateTime"
  df
})

# Convert the "DateTime" column to POSIXct format
df_list_hw <- lapply(df_list_hw, function(df) {
  df$DateTime <- ymd_hms(df$DateTime)
  df
})

# Add a "seconds" column representing seconds since the first observation
df_list_hw <- lapply(df_list_hw, function(df) {
  df$seconds <- as.numeric(df$DateTime - min(df$DateTime))
  df
})
```


#Reading in and manipulating frameview graphs 
```{r}
excel_file_frameview = "C:/Users/Ryan/Coding Projects/Computer Benchmark/Data/frameview_files.xlsx"

Frameview_GTAV <- read_excel(excel_file_frameview, sheet = "GTA5")
Frametime_ow <- read_excel(excel_file_frameview, sheet = "Overwatch")
Frametime_R6 <- read_excel(excel_file_frameview, sheet = "RainbowSix")
Frameview_Apex <- read_excel(excel_file_frameview, sheet = "r5apex")
Frameview_Destiny <- read_excel(excel_file_frameview, sheet = "destiny2")
Frameview_RL <- read_excel(excel_file_frameview, sheet = "RocketLeague")

Frameview_battlefront <- read_excel(excel_file_frameview, sheet = "starwarsbattlefrontii")
frameview_halo <- read_excel(excel_file_frameview, sheet = "HaloInfinite")
frameview_fortnite <- read_excel(excel_file_frameview, sheet = "FortniteClient")
frameview_cod <- read_excel(excel_file_frameview, sheet = "cod")

#list of dataframes 

df_list <- list(Frameview_GTAV, Frametime_ow, Frametime_R6, Frameview_Apex, Frameview_Destiny, Frameview_RL, Frameview_battlefront, frameview_halo, frameview_fortnite, frameview_cod)

names(df_list) <- c("gtav", "overwatch", "r6", "apex", "destiny", "rocket_league", "battlefront", "halo", "fortnite", "cod")

# Define the columns to select
cols_to_select <- c("TimeInSeconds", "MsBetweenPresents", "MsBetweenDisplayChange", "GPU1Clk(MHz)", "GPU1Util(%)", "GPU1Temp(C)", "AMDPwr(W) (API)", "CPUClk(MHz)", "CPUUtil(%)", "CPU Package Temp(C)", "CPU Package Power(W)")

# Apply the select statement to each data frame in the list
dfs_all <- lapply(df_list, function(df) select(df, cols_to_select))

# Add the seconds variable to each data frame in the list
dfs_all <- lapply(dfs_all, function(df) {
  df$seconds <- as.numeric(df$TimeInSeconds - min(df$TimeInSeconds))
  return(df)
})

#Way to thin out the observations in my dataset, although it makes no difference at large time intervals, once we zoom in on a specific time thinning out the data helps to smooth the time series graph and avoids it being so jagged  
#This specific code reports values of variables 3 times a second 
dfs_subset <- lapply(dfs_all, function(df) df[seq(1, nrow(df), by = 100), ])

rm(df_list)
```

#Temperature
```{r}
ggplot() +
  #geom_line(data = dfs_subset[["overwatch"]], aes(x = seconds, y = `GPU1Temp(C)`, color = "blue")) +
  #geom_line(data = df_list_hw[["overwatch"]], aes(x = seconds, y = GPU.Temperature...C., color = "red")) +

  geom_line(data = dfs_subset[["overwatch"]], aes(x = seconds, y = `CPU Package Temp(C)`), color = "red") +
  geom_line(data = df_list_hw[["overwatch"]], aes(x = seconds, y = CPU..Tctl.Tdie....C.))

  dfs_subset[["overwatch"]]$`CPU Package Temp(C)`
  df_list_hw[["overwatch"]]$CPU..Tctl.Tdie....C.
  
  geom_line(aes(y = GPU.PPT..W., color = "GPU"))
  
  
  
  geom_point(data = df2, aes(x = timestamp2, y = variable2), color = "red") +
  labs(title = "Variable Comparison", x = "Timestamp", y = "Variable Value")


dfs_subset["overwatch"]
```


