```{r}
library(tidyverse)
library(readxl)
library(lubridate) #for date extraction and manipulation
library(ggthemes)

excel_file_hwinfo = "C:/Users/Ryan/Coding Projects/Computer Benchmark/Data/hwinfo_test.xlsx"

timespy <- read_excel(excel_file_hwinfo, sheet = "hwinfo_timespy")
firestrike <- read_excel(excel_file_hwinfo, sheet = "hwinfo_firestrike_e")
heaven <- read_excel(excel_file_hwinfo, sheet = "hwinfo_heaven")
cinebench <- read_excel(excel_file_hwinfo, sheet = "hwinfo_cinebench")

#Creating a list of dataframes from above  
df_list <- list(timespy, heaven, cinebench, firestrike)

# Rename each data frame in the list to match its sheet name
names(df_list) <- c("Timespy", "Heaven", "Cinebench", "Firestrike")

# Remove the last 2 rows from each data frame
df_list <- lapply(df_list, function(df) head(df, -2))

# Convert all columns (except for the date column) to numeric then recombines original date variable to numeric dataset
df_list <- lapply(df_list, function(df) {
  df_num <- as.data.frame(lapply(df[-1], as.numeric))
  cbind(df[1], df_num)
})

# Rename the date column to "DateTime"
df_list <- lapply(df_list, function(df) {
  names(df)[1] <- "DateTime"
  df
})

# Convert the "DateTime" column to POSIXct format
df_list <- lapply(df_list, function(df) {
  df$DateTime <- ymd_hms(df$DateTime)
  df
})

# Add a "seconds" column representing seconds since the first observation
df_list <- lapply(df_list, function(df) {
  df$seconds <- as.numeric(df$DateTime - min(df$DateTime))
  df
})

#Creating a list of scores for that each benchmark achieved - needs to be updated once I want a new report
score <- list(19448, 5872, 20517, 26593)
names(score) <- c("Timespy", "Heaven", "Cinebench", "Firestrike")
```


#Power Consuption 
```{r}
power_plots <- list()

for (df_name in names(df_list)) {

power <- ggplot(df_list[[df_name]], aes(seconds)) +
  
  geom_line(aes(y = CPU.Package.Power..W., color = "CPU")) +
  
  geom_line(aes(y = GPU.PPT..W., color = "GPU")) +
  
  annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
         size = 4, color = "black", hjust = -.2, vjust = 1.5) +
  
    #Adding the average measure into the graph 
  annotate("text", x = -Inf, y = Inf,
       label = paste0("Avg CPU Power: ", round(mean(df_list[[df_name]]$CPU.Package.Power..W.), 1), " W", "\n",
                      "Avg GPU Temp: ", round(mean(df_list[[df_name]]$GPU.PPT..W.), 1), " W", "\n"),
       size = 2.5, color = "black", hjust = -1.2, vjust = 1.1) +
    
    labs(
      y = "Power Draw (Watts)",
      x = "Time (M:SS)", 
      title = paste0("Comparing Power Consumption of CPU and GPU in ", df_name)
    ) +
    
    scale_y_continuous(breaks = seq(0, 300, by = 50),
                       minor_breaks = seq(0, 300, by = 25),
                       limits = c(0, 300)) +
    
    scale_x_continuous(
      breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
      
      #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
      
      labels = function(x) sprintf("%2d:%02d", floor(x/60), x %% 60)
    ) +
    
    scale_color_manual(name = NULL, values = c("CPU" = "red", "GPU" = "blue")) +
    theme_bw() +
    
    theme(
         panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
         legend.position = c(0.85, 0.92),
         legend.direction = "horizontal", 
         legend.text = element_text(size = 6),
         legend.background = element_rect(fill = "grey99", color = "black", size = 0.5)) #makes a box around the legend and adds a fill! 

  power_plots[[df_name]] <- power
  rm(power)
}

power_plots[["Firestrike"]]
```


#GPU and CPU temperature 
```{r}
temperautre_plots <- list()

for (df_name in names(df_list)) {

temp <- ggplot(df_list[[df_name]], aes(seconds)) +
  
    geom_line(aes(y = CPU..Tctl.Tdie....C., color = "CPU")) +
    
    geom_line(aes(y = GPU.Temperature...C., color = "GPU")) +
  
    annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
         size = 4, color = "black", hjust = -.2, vjust = 1.5) +
  
      #Adding the average measure into the graph 
    annotate("text", x = -Inf, y = Inf,
       label = paste0("Avg CPU Temp: ", round(mean(df_list[[df_name]]$CPU..Tctl.Tdie....C.), 1), " *C", "\n",
                      "Avg GPU Temp: ", round(mean(df_list[[df_name]]$GPU.Temperature...C.), 1), " *C", "\n"),
       size = 2.5, color = "black", hjust = -1.2, vjust = 1.1) +
    
    labs(
      y = "Temperature (*C)",
      x = "Time (M:SS)", 
      title = paste0("Temperature of CPU and GPU over time in ", df_name)
    ) +
    
    scale_x_continuous(
      breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
      
      #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
      
      labels = function(x) sprintf("%02d:%02d", floor(x/60), x %% 60)
    ) +
    
    #scale_y_continuous(breaks = seq(40, 80, by = 5),
      #minor_breaks = seq(40, 80, by = 2.5),
      #limits = c(40, 80)) +
    
    scale_color_manual(name = NULL,
                       values = c("CPU" = "red", "GPU" = "blue")) +
    
    theme_bw() +
    
    theme(panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
         legend.position = c(0.85, 0.88),
         legend.direction = "horizontal",
         legend.text = element_text(size = 6),
         legend.background = element_rect(fill = "grey99", color = "black", size = 0.5)) #makes a box around the legend and adds a fill! 


  temperautre_plots[[df_name]] <- temp
  
  rm(temp)
}

temperautre_plots[["Timespy"]]
```


#Temperature and power consuption CPU
```{r}
temp_power_cpu_list <- list()

for (df_name in names(df_list)) {
  
temp_power_cpu <- ggplot(df_list[[df_name]], aes(seconds)) +
  
  geom_line(aes(y = CPU.Package.Power..W., color = "CPU Power")) +
  
  geom_line(aes(y = CPU..Tctl.Tdie....C., color = "CPU Temp")) +
  
  #A really cool function in R we can use to add not only text but shapes and lines to our graph 
  annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
         size = 4, color = "black", hjust = -.2, vjust = 1.5) +

      #Adding the average measure into the graph 
  annotate("text", x = -Inf, y = Inf,
       label = paste0("Avg CPU Power: ", round(mean(df_list[[df_name]]$CPU.Package.Power..W.), 1), " W", "\n",
                      "Avg CPU Temp: ", round(mean(df_list[[df_name]]$CPU..Tctl.Tdie....C.), 1), " *C", "\n"),
       size = 2.5, color = "black", hjust = -1.2, vjust = 1.1) +   
  
  
  #original solutuion for the above text
  #geom_text(aes(label = paste0("Score: ", score[df_name])), x = (max(df_list[[df_name]]$seconds) * .05), y = (max(df_list[[df_name]]$CPU.Package.Power..W.))) +
  
  labs(
    x = "Time (M:SS)", 
    title = paste0("CPU Power and Temperature Over Time in ", df_name)
  ) +
  
  scale_x_continuous(
    breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
    
    #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
    
    labels = function(x) sprintf("%02d:%02d", floor(x/60), x %% 60)
  ) +
  
  scale_y_continuous(name = "Power Draw (Watts)" ,
    sec.axis = sec_axis(~., name =  "Temperature (*C)")) +
    #breaks = seq(40, 80, by = 5),
    #minor_breaks = seq(40, 80, by = 2.5),
    #limits = c(40, 80)) +
  
  scale_color_manual(name = NULL,
                     values = c("CPU Power" = "red", "CPU Temp" = "blue")) +
  
  theme_bw() +
  
  theme(panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
       legend.position = c(0.8, 0.90),
       legend.direction = "horizontal", 
       legend.text = element_text(size = 6),
       legend.background = element_rect(fill = "grey99", color = "black", size = 0.5)) + #makes a box around the legend and adds a fill! 
  
  guides(fill = guide_legend(reverse = TRUE)) 

  temp_power_cpu_list[[df_name]] <- temp_power_cpu
  
  rm(temp_power_cpu)
}

temp_power_cpu_list[["Heaven"]]


#The "cairo = FALSE" parameter should get rid of the anti aliasing on the cinebench text
#ggsave(filename = "my_plot.png", dpi = 300, cairo = FALSE)
```


#Temperature and power consuption GPU
```{r}
temp_power_gpu_list <- list()

for (df_name in names(df_list)) {
  
temp_power_gpu <- ggplot(df_list[[df_name]], aes(seconds)) +
  
  geom_line(aes(y = GPU.PPT..W., color = "GPU Power")) +
  
  geom_line(aes(y = GPU.Temperature...C., color = "GPU Temp")) +
  
  annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
         size = 4, color = "black", hjust = -.2, vjust = 1.5) +  
  
      #Adding the average measure into the graph 
  annotate("text", x = -Inf, y = Inf,
       label = paste0("Avg GPU Power: ", round(mean(df_list[[df_name]]$GPU.PPT..W.), 1), " W", "\n",
                      "Avg GPU Temp: ", round(mean(df_list[[df_name]]$GPU.Temperature...C.), 1), " *C", "\n"),
       size = 2.5, color = "black", hjust = -1.2, vjust = 1.1) +    
  
  labs(
    x = "Time (M:SS)", 
    title = paste0("GPU Power and Temperature Over Time in ", df_name)
  ) +
  
  scale_x_continuous(
    breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
    
    #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
    
    labels = function(x) sprintf("%02d:%02d", floor(x/60), x %% 60)
  ) +
  
  scale_y_continuous(name = "Power Draw (Watts)" ,
    sec.axis = sec_axis(~., name =  "Temperature (*C)")) +
    #breaks = seq(40, 80, by = 5),
    #minor_breaks = seq(40, 80, by = 2.5),
    #limits = c(40, 80)) +
  
  scale_color_manual(name = NULL,
                     values = c("GPU Power" = "blue", "GPU Temp" = "red")) +
  
  theme_bw() +
  
  theme(panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
       legend.position = c(0.85, 0.85),
       legend.direction = "horizontal",
       legend.text = element_text(size = 6),
       legend.background = element_rect(fill = "grey99", color = "black", size = 0.5)) + #makes a box around the legend and adds a fill! 
  
  guides(fill = guide_legend(reverse = TRUE)) 

  temp_power_gpu_list[[df_name]] <- temp_power_gpu
  
  rm(temp_power_gpu)
}

temp_power_gpu_list[["Timespy"]]
```


#CPU and GPU utilization
```{r}
utilization_plots <- list()

for (df_name in names(df_list)) {
utilization <- ggplot(df_list[[df_name]], aes(seconds)) +
    geom_line(aes(y = Total.CPU.Usage...., color = "CPU")) +
    
    geom_line(aes(y = GPU.Utilization...., color = "GPU")) +
    
   annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
          size = 4, color = "black", hjust = -.2, vjust = 1.5) +
  
      #Adding the average measure into the graph 
    annotate("text", x = -Inf, y = Inf,
         label = paste0("Avg CPU Util: ", round(mean(df_list[[df_name]]$Total.CPU.Usage....), 1), "%", "\n",
                        "Avg GPU Util: ", round(mean(df_list[[df_name]]$GPU.Utilization....), 1), "%", "\n"),
         size = 2.5, color = "black", hjust = -1.5, vjust = 1.1) +
    
    labs(
      y = "Percent Utilized (%)",
      x = "Time (M:SS)", 
      title = paste0("Utilization of CPU and GPU Over Time in ", df_name)
    ) +
    
    scale_y_continuous(breaks = seq(0, 100, by = 20),
                       limits = c(0, 100)) +
    
    scale_x_continuous(
      breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
      
      #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
      
      labels = function(x) sprintf("%2d:%02d", floor(x/60), x %% 60),
      minor_breaks = seq(0, max(df_list[[df_name]]$seconds), by = 10),
    ) +
    
    scale_color_manual(name = NULL,
                       values = c("CPU" = "red", "GPU" = "blue")) +
    theme_bw() +
    
    theme(
         panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
         legend.position = c(0.80, 0.92),
         legend.direction = "horizontal",
         legend.text = element_text(size = 6),
         legend.background = element_rect(fill = "grey99", color = "black", size = 0.5)) #makes a box around the legend and adds a fill! 

  utilization_plots[[df_name]] <- utilization
  
  rm(utilization)

}

utilization_plots[["Timespy"]]
```


#Fan speed for both CPU and GPU coolers MKE SUYRE SIT WORK
```{r}

names(df_list[["cinebench"]])

fan_speed_list <- list()

for (df_name in names(df_list)) {
fan_speed <- ggplot(df_list[[df_name]], aes(seconds)) +
  
    geom_line(aes(y = CPU..RPM., color = "CPU Fan")) +
    
    geom_line(aes(y = GPU.Fan..RPM., color = "GPU Fan")) +

    geom_line(aes(y = System.2..RPM., color = "Case")) +  
  
    annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
         size = 4, color = "black", hjust = -.2, vjust = 1.5) +
  
      #Adding the average measure into the graph 
     annotate("text", x = -Inf, y = Inf,
         label = paste0("Avg CPU Fan: ", round(mean(df_list[[df_name]]$CPU..RPM.), 1), "\n",
                        "Avg GPU Fan: ", round(mean(df_list[[df_name]]$GPU.Fan..RPM.), 1), "\n",
                        "Avg Case Fan: ", round(mean(df_list[[df_name]]$System.2..RPM.), 1), "\n"),
         size = 2.5, color = "black", hjust = -1.4, vjust = 1.1) +  

    labs(
      y = "Fan speed (RPM)",
      x = "Time (M:SS)", 
      title = paste0("Fan Speed Over Time in ", df_name)
    ) +
    
    #scale_y_continuous(breaks = seq(0, 100, by = 20),
                       #limits = c(0, 100)) +
    
    scale_x_continuous(
      breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
      
      #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
      
      labels = function(x) sprintf("%2d:%02d", floor(x/60), x %% 60),
      minor_breaks = seq(0, max(df_list[[df_name]]$seconds), by = 10),
    ) +
    
    scale_color_manual(name = NULL, values = c("CPU Fan" = "red", "GPU Fan" = "blue", "Case" = "green")) +
    theme_bw() +
    
    theme(
         panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
         legend.position = c(0.75, 0.85),
         legend.direction = "horizontal", 
         legend.text = element_text(size = 6),
         legend.background = element_rect(fill = "grey99", color = "black", size = 0.5)) #makes a box around the legend and adds a fill! 

  fan_speed_list[[df_name]] <- fan_speed
  
  rm(fan_speed)
}

fan_speed_list[["Timespy"]]
```


#CPU Clock Speed graph
```{r}
clock_cpu_list <- list()

for (df_name in names(df_list)) {
  
clock_cpu <- ggplot(df_list[[df_name]], aes(seconds)) +
  geom_line(aes(y = Core.Clocks..avg...MHz.), color = "red") +
  
  annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
           size = 4, color = "black", hjust = -.2, vjust = 1.5) +
  
#Adding the average measure into the graph 
  annotate("text", x = -Inf, y = Inf,
       label = paste0("Avg CPU clk: ", round(mean(df_list[[df_name]]$Core.Clocks..avg...MHz.), 1), "\n"),
       size = 2.5, color = "black", hjust = -1.5, vjust = 1.1) +
  
  labs(
    y = "CPU Speed (MHz)", 
    x = "Time (M:SS)", 
    title = paste0("CPU Clock Speed During ", df_name, " Run")
  ) +
  
  scale_x_continuous(
    breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
    
    #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
    labels = function(x) sprintf("%02d:%02d", floor(x/60), x %% 60)
  ) +
  
  #scale_y_continuous(
    #breaks = seq(3500, 5500, by = 250),
    #limits = c(3500, 5500),
    #minor_breaks = seq(3500, 5500, by = 125)) +
  
  #scale_color_manual(name = "Measures",
                     #value = "Core.Clocks..avg...MHz." = "blue") +
  
  theme_bw() +
  
  theme(panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
       legend.background = element_rect(fill = "grey99", color = "black", size = 0.5))  #makes a box around the legend and adds a fill! 

  clock_cpu_list[[df_name]] <- clock_cpu
  
  rm(clock_cpu)
}

clock_cpu_list[["Cinebench"]]
```

#GPU Clock Speed graph
```{r}
clock_gpu_list <- list()

for (df_name in names(df_list)) {
  
clock_gpu <- ggplot(df_list[[df_name]], aes(seconds)) +
  geom_line(aes(y = GPU.Clock..MHz.), color = "red") +
  
  annotate("text", x = -Inf, y = Inf, label = paste0("Score: ", score[[df_name]]), 
           size = 4, color = "black", hjust = -.2, vjust = 1.5) +
  
#Adding the average measure into the graph 
  annotate("text", x = -Inf, y = Inf,
       label = paste0("Avg GPU clk: ", round(mean(df_list[[df_name]]$GPU.Clock..MHz.), 1), "\n"),
       size = 2.5, color = "black", hjust = -1.5, vjust = 1.1) +
  
  labs(
    y = "GPU Speed (MHz)", 
    x = "Time (M:SS)", 
    title = paste0("GPU Clock Speed During ", df_name, " Run")
  ) +
  
  scale_x_continuous(
    breaks = seq(0, max(df_list[[df_name]]$seconds), by = 20),
    
    #sprintf() is a function in R that allows you to format strings with placeholders for variables. It takes two arguments: the format string and the variables to substitute into the string. The format string is a character string that includes placeholders for the variables.
    labels = function(x) sprintf("%02d:%02d", floor(x/60), x %% 60)
  ) +
  
  #scale_y_continuous(
    #breaks = seq(3500, 5500, by = 250),
    #limits = c(3500, 5500),
    #minor_breaks = seq(3500, 5500, by = 125)) +
  
  #scale_color_manual(name = "Measures",
                     #value = "Core.Clocks..avg...MHz." = "blue") +
  
  theme_bw() +
  
  theme(panel.grid.minor.y = element_line(color = "gray", linetype = "dotted"),
       legend.background = element_rect(fill = "grey99", color = "black", size = 0.5))  #makes a box around the legend and adds a fill! 

  clock_gpu_list[[df_name]] <- clock_gpu
  
  rm(clock_gpu)
}

clock_gpu_list[["Heaven"]]
```



```{r eval=FALSE, include=FALSE}
# Itterating over each list of graphs above and save them individually as a png for a report 

#Create a list of lists with all the graphs we created above to loop through them and save each indivudal graph to its appropriate game file
List_of_list <- list(clock_gpu_list, clock_cpu_list, fan_speed_list, utilization_plots, temp_power_gpu_list, temp_power_cpu_list, temperautre_plots, power_plots)

#Just adding names to the above lists to make looping through them easier 
names(List_of_list) <- c("clock_gpu_list", "clock_cpu_list", "fan_speed_list", "utilization_plots", "temp_power_gpu_list", "temp_power_cpu_list", "temperautre_plots", "power_plots")

# Defining the path we want to initally save all of the graphs before we sort by game 
path_name <- "C:/Users/Ryan/Coding Projects/Computer Benchmark/unsorted synthetic graphs"

# Looping through each list saved in List_of_list then getting the number of graphs saved in that specific list (format of numbers is 1,2,3,4, 1,2,3,4,5,1,2,3,4,5,ect through each list of graphs)
#Then we extract the game name from each individual list to name the file later 
#Then we create the file name based on the list name from List_of_list and it's specific game graph we're saving 
for (name_list in seq_along(List_of_list)) {
  for (i in seq_along(List_of_list[[name_list]])) {
    
    game_name <- names(List_of_list[[name_list]][i])
                                       
    file_name <- paste0(names(List_of_list)[name_list], " - ", game_name, ".png")
    
    ggsave(List_of_list[[name_list]][[i]], file = file.path(path_name, file_name))
  }
}
```